#!/bin/bash
set -e

# @cmd Build core
build.core() {
    yarn --cwd js workspace @jsona/core build
}

# @cmd Build util-types
build.util-types() {
    yarn --cwd js workspace @jsona/util-types build
}

# @cmd Build lsp
build.lsp() {
    yarn --cwd js workspace @jsona/lsp build
}

# @cmd Build lsp
build() {
    build.core
    build.util-types
    build.lsp
}


eval "$(argc --argc-eval $0 "$@")"
