[tasks.build]
command = "wasm-pack"
args = ["build", "-t", "nodejs"]
dependencies = ["clean"]

[tasks.clean]
command = "rm"
args = ["-rf", "pkg"]

[tasks.test]
command = "node"
args = ["./tests/test.js"]