name: VSCode Nightly release

on:
  push:
    branches:
    - vscode-nightly

jobs:
  nightly-release:
    name: Nightly publish to Github Releases And Marketplace

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - uses: extractions/setup-crate@v1
      with:
        owner: sigoden
        name: argc

    - name: Install Rust Toolchain Components
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - uses: Swatinem/rust-cache@v2

    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'

    - run: corepack enable

    - run: argc prepare

    - name: Set nightly version
      run: |
        version=$(node -e 'console.log(require("./package.json").version)')
        semver=( $(echo $version | tr '.' ' ') )
        patch=${{ github.run_number }}
        if [[ ${semver[0]} -eq 0 ]]; then
            version_new=0.$(( ${semver[1]} + 1 )).$((patch * 2))
        else
            version_new=$(( ${semver[0]} + 1 )).0.$((patch * 2))
        fi
        sed -i 's/^  "version": "'$version'",/  "version": "'$version_new'",/' package.json
      working-directory: editors/vscode

    - run: argc build-js

    - run: yarn package -o jsona.vsix --pre-release
      working-directory: editors/vscode
    
    - name: Update Nightly Release
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: 'VSCODE Nightly Release $$'
        tag_name: nightly
        draft: false
        prerelease: true
        body: 'This is a nightly release of the vscode-jsona extension.'
        files: editors/vscode/jsona.vsix

    - name: Publish Extension
      run: npx vsce publish --pat ${{ secrets.VSCODE_MARKETPLACE_TOKEN }} --packagePath jsona.vsix --pre-release
      working-directory: editors/vscode